# Generated by Django 4.1 on 2022-08-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_auto_20220803_1709"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
