# Generated by Django 4.1 on 2022-08-04 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0006_alter_chat_id_alter_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="is_archived",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="user_archived",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="pinned",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="user_pinned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="unmuted",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="user_unmuted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
